name: swarm_rover_system_staff
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  go_router: ^6.0.9
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.1.3
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  window_manager: ^0.3.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.5.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.0
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
